/**
 * Headless Bedrock Server Wardrobe Addon Generator
 * Pure in-memory JSZip generator for multi-skin server addons
 */
import JSZip from 'jszip';
import { generateUUID, generateRandomId } from '../../modules/utils.js';
import { AppError, ErrorCode } from '../errors/AppError.js';

/**
 * Generate a complete Server Wardrobe .mcaddon in-memory
 * @param {Object} config
 * @param {Array} config.wardrobes
 * @param {Array<number>} config.addonVersion
 * @param {Array<string>} config.authors
 * @param {Function} [config.fetchTemplate] - Optional template fetcher
 * @returns {Promise<{ zip: JSZip, namespace: string, outfitCount: number }>}
 */
export async function createWardrobeAddon({
  wardrobes = [],
  addonVersion = [1, 0, 0],
  authors = ['ServerTeam', 'SkinProject'],
  fetchTemplate = null
}) {
  if (!Array.isArray(wardrobes) || wardrobes.length === 0) {
    throw new AppError(ErrorCode.WARDROBE_EMPTY);
  }

  const zip = new JSZip();
  const namespace = generateRandomId(10);
  const bpUuid = generateUUID();
  const rpUuid = generateUUID();

  // Load base templates if fetcher provided or browser environment
  const templateFiles = [
    'ZirconX-SKIN_BP/items/zxskin.json',
    'ZirconX-SKIN_RP/attachables/zxskin.json',
    'ZirconX-SKIN_RP/materials/entity.material',
    'ZirconX-SKIN_RP/textures/items/skin_item.png',
    'ZirconX-SKIN_RP/textures/item_texture.json',
    'packicon.png'
  ];

  for (const tPath of templateFiles) {
    try {
      let blob = null;
      if (typeof fetchTemplate === 'function') {
        blob = await fetchTemplate(tPath);
      } else if (typeof fetch === 'function' && typeof import.meta !== 'undefined' && import.meta.env?.BASE_URL) {
        const resp = await fetch(`${import.meta.env.BASE_URL}templates/${tPath}`);
        if (resp.ok) blob = await resp.blob();
      }
      if (blob) {
        if (tPath === 'packicon.png') {
          zip.file('ZirconX-SKIN_BP/pack_icon.png', blob);
          zip.file('ZirconX-SKIN_RP/pack_icon.png', blob);
        } else {
          zip.file(tPath, blob);
        }
      }
    } catch (_) {}
  }

  // 1. Generate Script API main.js
  const sanitizedPlayerData = wardrobes.map(w => ({
    uniq: w.uniq,
    name: w.name,
    allowUsername: w.allowUsername || [],
    skinlist: (w.skinlist || []).map(s => ({
      name: s.name,
      action: s.action
    }))
  }));

  const scriptContent = `/**
 * Minecraft Bedrock Server Wardrobe System
 * Generated by ZirconX Skin Project
 */
import { world, system } from '@minecraft/server';
import { ActionFormData, MessageFormData } from '@minecraft/server-ui';

let playerData = ${JSON.stringify(sanitizedPlayerData, null, 2)};

world.beforeEvents.itemUse.subscribe(event => {
    let source = event.source;
    if (event.itemStack.typeId === "zxskin:skin" || event.itemStack.typeId === "zirconx:skin" || event.itemStack.typeId === "zxd44:skin") {
        system.run(() => titleScreen(source));
    }

    function titleScreen(player) {
        const wardrobeData = playerData.filter(e => e.allowUsername.includes(player.name));
        const form = new MessageFormData()
            .title("ตู้เสื้อผ้า")
            .body("ระบบจัดการและเปลี่ยนชุดตัวละคร")
            .button1(wardrobeData.length > 0 ? "เปิดตู้เสื้อผ้า" : "§cไม่มีสิทธิ์เข้าถึงตู้เสื้อผ้า")
            .button2("ชุดเริ่มต้น");

        form.show(player).then(choice => {
            if (choice.selection === 0) {
                if (wardrobeData.length > 0) wardrobeSelection(player, wardrobeData);
                else player.runCommand("title @s actionbar §cคุณไม่มีสิทธิ์เข้าถึงตู้เสื้อผ้า");
            } else {
                if (choice.canceled) return;
                player.runCommand("title @s actionbar §aเปลี่ยนเป็นชุดเริ่มต้นเรียบร้อย");
                return player.runCommand('event entity @s ${namespace}:humanoid');
            }
        });
    }

    function wardrobeSelection(player, wardrobe) {
        const form = new ActionFormData()
            .title('เลือกตู้เสื้อผ้า')
            .body('สวัสดี §e' + player.name + '§r กรุณาเลือกตู้ที่ต้องการ');

        wardrobe.forEach(data => {
            form.button(data.name);
        });

        form.show(player).then(choice => {
            if (choice.canceled) return;
            return skinSelection(player, wardrobe[choice.selection].skinlist, wardrobe);
        });
    }

    function skinSelection(player, skinlist, wardrobe) {
        const form = new ActionFormData()
            .title('เลือกชุดสกิน')
            .body('เลือกชุดที่ต้องการสวมใส่');

        skinlist.forEach(skindata => {
            form.button(skindata.name);
        });

        form.show(player).then(choice => {
            if (choice.canceled) return wardrobeSelection(player, wardrobe);
            player.runCommand('title @s actionbar §aเปลี่ยนชุดเป็น "' + skinlist[choice.selection].name + '" เรียบร้อยแล้ว');
            player.runCommand('event entity @s ${namespace}:' + skinlist[choice.selection].action);
        });
    }
});
`;

  zip.file('ZirconX-SKIN_BP/scripts/main.js', scriptContent);

  // 2. Manifests (BP & RP)
  const bpManifest = {
    format_version: 2,
    metadata: {
      authors,
      generated_with: { "ZirconX_Project": ["2.0.0"] }
    },
    header: {
      name: `ตู้เสื้อผ้า ZirconX ${addonVersion.join(".")}`,
      description: "ระบบตู้เสื้อผ้าและสลับชุดสำหรับเซิร์ฟเวอร์ พัฒนาโดย ZirconX",
      min_engine_version: [1, 21, 60],
      uuid: bpUuid,
      version: addonVersion
    },
    modules: [
      { type: "data", uuid: generateUUID(), version: addonVersion },
      { type: "script", language: "javascript", uuid: generateUUID(), entry: "scripts/main.js", version: addonVersion }
    ],
    dependencies: [
      { uuid: rpUuid, version: addonVersion },
      { module_name: "@minecraft/server", version: "2.1.0" },
      { module_name: "@minecraft/server-ui", version: "2.0.0" }
    ]
  };

  const rpManifest = {
    format_version: 2,
    metadata: {
      authors,
      generated_with: { "ZirconX_Project": ["2.0.0"] }
    },
    header: {
      name: `ตู้เสื้อผ้า ZirconX ${addonVersion.join(".")}`,
      description: "ระบบตู้เสื้อผ้าและสลับชุดสำหรับเซิร์ฟเวอร์ พัฒนาโดย ZirconX",
      min_engine_version: [1, 21, 60],
      uuid: rpUuid,
      version: addonVersion
    },
    modules: [
      { type: "resources", uuid: generateUUID(), version: addonVersion }
    ],
    dependencies: [
      { uuid: bpUuid, version: addonVersion }
    ]
  };

  zip.file('ZirconX-SKIN_BP/manifest.json', JSON.stringify(bpManifest, null, 2));
  zip.file('ZirconX-SKIN_RP/manifest.json', JSON.stringify(rpManifest, null, 2));

  // 3. Render Controller & Player Entities
  const allOutfits = [];
  wardrobes.forEach(w => {
    (w.skinlist || []).forEach(s => allOutfits.push(s));
  });

  const renderControllerJson = {
    format_version: "1.10.0",
    render_controllers: {
      "controller.render.player.1st_person": {
        arrays: {
          textures: {
            "array.skins": ["Texture.default", ...allOutfits.map(o => `Texture.${o.action}`)]
          }
        },
        geometry: "Geometry.default",
        materials: [{ "*": "Material.default" }],
        textures: ["array.skins[query.mark_variant]"],
        part_visibility: [
          { "*": false },
          { rightArm: "query.get_equipped_item_name == ''" },
          { rightSleeve: "query.get_equipped_item_name == ''" }
        ]
      },
      "controller.render.skinpack": {
        geometry: "geometry.default",
        materials: [{ "*": "Material.default" }],
        textures: ["array.skins[query.mark_variant]"],
        part_visibility: [{ "*": true }, { head: true }],
        arrays: {
          textures: {
            "array.skins": ["Texture.default", ...allOutfits.map(o => `Texture.${o.action}`)]
          },
          geometries: { "array.geo": ["Geometry.default"] }
        }
      },
      "controller.render.player.spectator": {
        geometry: "'array.geo[query.mark_variant != undefined ? query.mark_variant : 0]'",
        materials: [{ "*": "Material.spectator" }],
        textures: ["array.skins[query.mark_variant]"],
        part_visibility: [{ "*": false }, { head: true }],
        ignore_lighting: true,
        light_color_multiplier: 2.5,
        overlay_color: { r: 0, g: 0.2, b: 0.5, a: 0.8 },
        color: { r: 0.7, g: 0.9, b: 1, a: 0.5 }
      }
    }
  };

  const playerEntityRpJson = {
    format_version: "1.10.0",
    "minecraft:client_entity": {
      description: {
        identifier: "minecraft:player",
        materials: {
          default: "entity_alphatest",
          solid: "entity_alphatest",
          spectator: "player_spectator"
        },
        textures: {
          default: "textures/entity/alex"
        },
        geometry: {
          default: "geometry.humanoid",
          cape: "geometry.cape"
        },
        render_controllers: [
          { "controller.render.player.1st_person": "variable.is_first_person && !q.is_spectator" },
          { "controller.render.skinpack": "!variable.is_first_person && !variable.map_face_icon && !q.is_spectator" },
          { "controller.render.player.spectator": "q.is_spectator" }
        ],
        enable_attachables: true
      }
    }
  };

  const playerEntityBpJson = {
    format_version: "1.21.60",
    "minecraft:entity": {
      description: {
        identifier: "minecraft:player",
        is_spawnable: false,
        is_summonable: false,
        is_experimental: false
      },
      component_groups: {
        [`${namespace}:humanoid`]: {
          "minecraft:mark_variant": { value: 0 }
        }
      },
      components: {
        "minecraft:type_family": { family: ["player"] }
      },
      events: {
        [`${namespace}:humanoid`]: {
          add: { component_groups: [`${namespace}:humanoid`] }
        }
      }
    }
  };

  // Populate variants in RP & BP
  allOutfits.forEach((outfit, idx) => {
    const markVal = idx + 1;
    playerEntityRpJson["minecraft:client_entity"].description.textures[outfit.action] = `textures/skin/${outfit.action}`;

    playerEntityBpJson["minecraft:entity"].component_groups[`${namespace}:${outfit.action}`] = {
      "minecraft:mark_variant": { value: markVal }
    };
    playerEntityBpJson["minecraft:entity"].events[`${namespace}:${outfit.action}`] = {
      add: { component_groups: [`${namespace}:${outfit.action}`] }
    };

    // Add skin texture file
    if (outfit.blob) {
      zip.file(`ZirconX-SKIN_RP/textures/skin/${outfit.action}.png`, outfit.blob);
    } else if (outfit.skinURL && typeof fetch === 'function') {
      zip.file(`ZirconX-SKIN_RP/textures/skin/${outfit.action}.png`, fetch(outfit.skinURL).then(r => r.blob()));
    } else if (outfit.base64) {
      zip.file(`ZirconX-SKIN_RP/textures/skin/${outfit.action}.png`, outfit.base64, { base64: true });
    }
  });

  zip.file('ZirconX-SKIN_RP/render_controllers/player.render_controller.json', JSON.stringify(renderControllerJson, null, 2));
  zip.file('ZirconX-SKIN_RP/entity/player.entity.json', JSON.stringify(playerEntityRpJson, null, 2));
  zip.file('ZirconX-SKIN_BP/entities/player.json', JSON.stringify(playerEntityBpJson, null, 2));

  // 4. Localization texts (Thai & English)
  const wardrobeLang = [
    "## ZirconX Wardrobe Localization",
    "pack.name=ZirconX Wardrobe",
    "pack.description=Server Wardrobe System by ZirconX",
    "item.zxskin:skin.name=ตู้เสื้อผ้า (Wardrobe)",
    "item.zxskin:skin=ตู้เสื้อผ้า (Wardrobe)",
    "item.zirconx:skin.name=ตู้เสื้อผ้า (Wardrobe)",
    "item.zirconx:skin=ตู้เสื้อผ้า (Wardrobe)",
    "item.zxd44:skin.name=ตู้เสื้อผ้า (Wardrobe)",
    "item.zxd44:skin=ตู้เสื้อผ้า (Wardrobe)"
  ].join('\n') + '\n';
  const wardrobeLangsJson = JSON.stringify(['en_US', 'th_TH'], null, 2);

  zip.file('ZirconX-SKIN_RP/texts/en_US.lang', wardrobeLang);
  zip.file('ZirconX-SKIN_RP/texts/th_TH.lang', wardrobeLang);
  zip.file('ZirconX-SKIN_RP/texts/languages.json', wardrobeLangsJson);

  zip.file('ZirconX-SKIN_BP/texts/en_US.lang', wardrobeLang);
  zip.file('ZirconX-SKIN_BP/texts/th_TH.lang', wardrobeLang);
  zip.file('ZirconX-SKIN_BP/texts/languages.json', wardrobeLangsJson);

  return {
    zip,
    namespace,
    outfitCount: allOutfits.length
  };
}
